name: waterbill
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  firebase_core: ^2.31.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.15.10
  firebase_auth: ^4.19.5
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  syncfusion_flutter_charts: ^25.2.4
  collection: ^1.18.0

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo.png
  fonts:
  - family: Grandstander
    fonts: 
    - asset: assets/fonts/Grandstander-ExtraBold.ttf
