name: waterbill
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  firebase_core: ^2.31.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.15.10
  firebase_auth: ^4.19.5
  syncfusion_flutter_charts: ^25.2.4
  collection: ^1.18.0
  pdf: ^3.10.8
  path_provider: ^2.1.3
  open_file: ^3.3.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo.png
  fonts:
  - family: Grandstander
    fonts: 
    - asset: assets/fonts/Grandstander-ExtraBold.ttf
